services:
  reservations:
    image: sleepr_reservations
    container_name: sleepr_reservations
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    image: sleepr_auth
    container_name: sleepr_auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  payments:
    image: sleepr_payments
    container_name: sleepr_payments
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
  notifications:
    image: sleepr_notifications
    container_name: sleepr_notifications
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    container_name: sleepr_mongo
    # This command will stop mongo from flooding the terminal with hard to read logs
    command: mongod --quiet --logpath /dev/null
